Fixed link error (undefined reference to `ViewCanvas::GmatGLCanvasAttribs') on Linux which caused by previous change.
git-svn-id: svn+ssh://svn.code.sf.net/p/gmat/code/trunk@10549 222415a0-0dc2-4184-858d-a27cde375526

Former-commit-id: 9c0937d9e9fc4ba961d1574a63494e31a0c9331f